repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yam
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1 # seed-isort-config version independent from isort
    hooks:
    -   id: seed-isort-config
- repo: https://github.com/timothycrosley/isort
    rev: v5.3.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
-   repo: https://github.com/Locas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: remove-crlf
    -   id: forbid-crlf
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle