version: "3.8"
services:

  # IDE in browser
  ide:
    build:
      context: .
      target: ide
    image: cookiecutter_dev
    container_name: cookiecutter_dev
    ports:
      - 8123:8123
      - 8080:8080
      - 40000:40000
    volumes:
      - .:/home/root/app
      - pre-commit:/root/.cache/pre-commit
      - poetry-cache:/root/.cache/pypoetry
      - $HOME/.gitconfig:/root/.gitconfig
      - $SSH_AUTH_SOCK:/tmp/authsock
    environment:
      SSH_AUTH_SOCK: /tmp/authsock
    restart: unless-stopped
    command: "code-server --auth none --bind-addr 0.0.0.0:8123 /home/root/app"
    tty: true

  dev:
    build:
      context: .
      target: dev
    image: project_blueprint_dev_image
    container_name: project_blueprint
    volumes:
      - .:/home/root/app/.
      - vscode-extensions:/root/.vscode-server/extensions
    command: bash -c "poetry run python"
    tty: true

volumes:
  vscode-extensions:
  pre-commit:
  poetry-cache: